
/**     @property/Object process
@spare `Library Documentation`
    @remote `https://nodejs.org/api/process.html#process_process`
@spare `Exit Codes`
    @remote `https://nodejs.org/api/process.html#process_exit_codes`
@spare `Signal Events`
    @remote `https://nodejs.org/api/process.html#process_signal_events`
@event exit
    @remote `https://nodejs.org/api/process.html#process_event_exit`
@event beforeExit
    @remote `https://nodejs.org/api/process.html#process_event_beforeexit`
@event uncaughtException
    @remote `https://nodejs.org/api/process.html#process_event_uncaughtexception`
@Function abort
    @remote `https://nodejs.org/api/process.html#process_process_abort`
@Function chdir
    @remote `https://nodejs.org/api/process.html#process_process_chdir_directory`
@Function cwd
    @remote `https://nodejs.org/api/process.html#process_process_cwd`
@Function exit
    @remote `https://nodejs.org/api/process.html#process_process_exit_code`
@Function getgid
    @remote `https://nodejs.org/api/process.html#process_process_getgid`
@Function setgid
    @remote `https://nodejs.org/api/process.html#process_process_setgid_id`
@Function getuid
    @remote `https://nodejs.org/api/process.html#process_process_getuid`
@Function setuid
    @remote `https://nodejs.org/api/process.html#process_process_setuid_id`
@Function getgroups
    @remote `https://nodejs.org/api/process.html#process_process_getgroups`
@Function setgroups
    @remote `https://nodejs.org/api/process.html#process_process_setgroups_groups`
@Function initgroups
    @remote `https://nodejs.org/api/process.html#process_process_initgroups_user_extra_group`
@Function kill
    @remote `https://nodejs.org/api/process.html#process_process_kill_pid_signal`
@Function memoryUsage
    @remote `https://nodejs.org/api/process.html#process_process_memoryusage`
@Function nextTick
    @remote `https://nodejs.org/api/process.html#process_process_nexttick_callback`
@Function umask
    @remote `https://nodejs.org/api/process.html#process_process_umask_mask`
@Function uptime
    @remote `https://nodejs.org/api/process.html#process_process_uptime`
@Function hrtime
    @remote `https://nodejs.org/api/process.html#process_process_hrtime`
@Stream.Writable stdout
    @remote `https://nodejs.org/api/process.html#process_process_stdout`
@Stream.Writable stderr
    @remote `https://nodejs.org/api/process.html#process_process_stderr`
@Stream.Readable stdin
    @remote `https://nodejs.org/api/process.html#process_process_stdin`
@Array[String] argv
    @remote `https://nodejs.org/api/process.html#process_process_argv`
@String execPath
    @remote `https://nodejs.org/api/process.html#process_process_execpath`
@Array[String] execArgv
    @remote `https://nodejs.org/api/process.html#process_process_execargv`
@String env
    @remote `https://nodejs.org/api/process.html#process_process_env`
@Number exitCode
    @remote `https://nodejs.org/api/process.html#process_process_exitcode`
@String version
    @remote `https://nodejs.org/api/process.html#process_process_version`
@Object versions
    @remote `https://nodejs.org/api/process.html#process_process_versions`
@Object config
    @remote `https://nodejs.org/api/process.html#process_process_config`
@Number pid
    @remote `https://nodejs.org/api/process.html#process_process_pid`
@String title
    @remote `https://nodejs.org/api/process.html#process_process_title`
@String arch
    @remote `https://nodejs.org/api/process.html#process_process_arch`
@String platform
    @remote `https://nodejs.org/api/process.html#process_process_platform`
@Object mainModule
    @remote `https://nodejs.org/api/process.html#process_process_mainmodule`
*/
